import { Options } from "./props.js";

const COMMON_PROPS: Options = {
	localeMatcher: {
		values: {
			"Lookup": "lookup",
			"Best Fit": "best fit"
		},
		labelText: "Locale matching algorithm",
		defaultValue: "best fit"
	},
	numberingSystem: {
		values: {
			Adlam: "adlm",
			Ahom: "ahom",
			"Arabic-Indic": "arab",
			"Extended Arabic-Indic": "arabext",
			"Armenian uppercase": "armn",
			"Armenian lowercase": "armnlow",
			Balinese: "bali",
			Bengali: "beng",
			Bhaiksuki: "bhks",
			Brahmi: "brah",
			Chakma: "cakm",
			Cham: "cham",
			Cyrillic: "cyrl",
			Devanagari: "deva",
			Ethiopic: "ethi",
			"Financial numerals": "finance",
			"Full width": "fullwide",
			Georgian: "geor",
			"Gunjala Gondi": "gong",
			"Masaram Gondi": "gonm",
			"Greek uppercase": "grek",
			"Greek lowercase": "greklow",
			Gujarati: "gujr",
			Gurmukhi: "guru",
			"Han-character": "hanidays",
			"Chinese ideographs decimal": "hanidec",
			"Simplified Chinese": "hans",
			"Simplified Chinese financial": "hansfin",
			"Traditional Chinese": "hant",
			"Traditional Chinese financial": "hantfin",
			Hebrew: "hebr",
			"Pahawh Hmong": "hmng",
			"Nyiakeng Puachue Hmong": "hmnp",
			Javanese: "java",
			Japanese: "jpan",
			"Japanese financial": "jpanfin",
			"Japanese Gannen": "jpanyear",
			"Kayah Li": "kali",
			Khmer: "khmr",
			Kannada: "knda",
			"Tai Tham Hora": "lana",
			"Tai Tham": "lanatham",
			Lao: "laoo",
			Latin: "latn",
			Lepcha: "lepc",
			Limbu: "limb",
			"Mathematical bold": "mathbold",
			"Mathematical double-struck": "mathdbl",
			"Mathematical monospace": "mathmono",
			"Mathematical sans-serif bold": "mathsanb",
			"Mathematical sans-serif": "mathsans",
			Malayalam: "mlym",
			Modi: "modi",
			Mongolian: "mong",
			Mro: "mroo",
			"Meetei Mayek": "mtei",
			Myanmar: "mymr",
			"Myanmar Shan": "mymrshan",
			"Myanmar Tai Laing": "mymrtlng",
			Native: "native",
			Newa: "newa",
			"N'Ko": "nkoo",
			"Ol Chiki": "olck",
			Oriya: "orya",
			Osmanya: "osma",
			"Hanifi Rohingya": "rohg",
			"Roman uppercase": "roman",
			"Roman lowercase": "romanlow",
			Saurashtra: "saur",
			Sharada: "shrd",
			Khudawadi: "sind",
			"Sinhala Lith": "sinh",
			Sora_Sompeng: "sora",
			Sundanese: "sund",
			Takri: "takr",
			"New Tai Lue": "talu",
			Tamil: "taml",
			"Modern Tamil decimal": "tamldec",
			Telugu: "telu",
			Thai: "thai",
			Tirhuta: "tirh",
			Tibetan: "tibt",
			Traditional: "traditio",
			Vai: "vaii",
			"Warang Citi": "wara",
			Wancho: "wcho"
		},
		labelText: "Numbering System"
	}
};

export default COMMON_PROPS;