import { Options } from "./props.js";

const COMMON_PROPS: Options = {
	localeMatcher: {
		values: {
			"Lookup": "lookup",
			"Best Fit": "best fit"
		},
		labelText: "Locale matching algorithm",
		defaultValue: "best fit"
	},
	numberingSystem: {
		values: {
			"Adlam": "adlm",
			"Ahom": "ahom",
			"Arabic-Indic": "arab",
			"Extended Arabic-Indic": "arabext",
			"Balinese": "bali",
			"Bengali": "beng",
			"Bhaiksuki": "bhks",
			"Brahmi": "brah",
			"Chakma": "cakm",
			"Cham": "cham",
			"Devanagari": "deva",
			"Dives Akuru": "diak",
			"Full width": "fullwide",
			"Garay": "gara",
			"Gunjala Gondi": "gong",
			"Masaram Gondi": "gonm",
			"Gujarati": "gujr",
			"Gurung Khema": "gukh",
			"Gurmukhi": "guru",
			"Chinese ideographs decimal": "hanidec",
			"Pahawh Hmong": "hmng",
			"Nyiakeng Puachue Hmong": "hmnp",
			"Javanese": "java",
			"Kayah Li": "kali",
			"Kawi": "kawi",
			"Khmer": "khmr",
			"Kannada": "knda",
			"Kirat Rai": "krai",
			"Tai Tham Hora (secular)": "lana",
			"Tai Tham Tham (ecclesiastical)": "lanatham",
			"Lao": "laoo",
			"Latin": "latn",
			"Lepcha": "lepc",
			"Limbu": "limb",
			"Mathematical bold": "mathbold",
			"Mathematical double-struck": "mathdbl",
			"Mathematical monospace": "mathmono",
			"Mathematical sans-serif bold": "mathsanb",
			"Mathematical sans-serif": "mathsans",
			"Malayalam": "mlym",
			"Modi": "modi",
			"Mongolian": "mong",
			"Mro": "mroo",
			"Meetei Mayek": "mtei",
			"Myanmar": "mymr",
			"Myanmar Eastern Pwo Karen": "mymrepka",
			"Myanmar Pao": "mymrpao",
			"Myanmar Shan": "mymrshan",
			"Myanmar Tai Laing": "mymrtlng",
			"Nag Mundari": "nagm",
			"Newa": "newa",
			"N'Ko": "nkoo",
			"Ol Chiki": "olck",
			"Ol Onal": "onao",
			"Oriya": "orya",
			"Osmanya": "osma",
			"Legacy computing outlined": "outlined",
			"Hanifi Rohingya": "rohg",
			"Saurashtra": "saur",
			"Legacy computing segmented": "segment",
			"Sharada": "shrd",
			"Khudawadi": "sind",
			"Sinhala Lith": "sinh",
			"Sora_Sompeng": "sora",
			"Sundanese": "sund",
			"Sunuwar": "sunu",
			"Takri": "takr",
			"New Tai Lue": "talu",
			"Modern Tamil decimal": "tamldec",
			"Tangsa": "tnsa",
			"Telugu": "telu",
			"Thai": "thai",
			"Tirhuta": "tirh",
			"Tibetan": "tibt",
			"Tolong Siki": "tols",
			"Vai": "vaii",
			"Warang Citi": "wara",
			"Wancho": "wcho"
		},
		labelText: "Numbering System"
	}
};

export default COMMON_PROPS;